### ISSUE TITLE
i am getting error in crudmaker  my project in laravel 5.4.*

### ISSUE THREAD

**Issue by sureshPprajapati** [GrafiteInc/CrudMaker#42]
hi, i am getting error when i run my laravel project 
**error : Call to undefined function app_namespace() in crudmaker.php line 37**
my php version is 7.0.29

**Comment by mlantz** [comment]
If you're using version 1.2 of the package we no longer support it. We're currently only supporting version 1.4 which works with Laravel 5.6+
